--- #YAML:1.0
name:                Bundle-MasteringPerl
version:             20070706
abstract:            install all modules mentioned in Mastering Perl
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
    Test::Pod:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - brian d foy <bdfoy@cpan.org>
